### ISSUE TITLE
[Docs]: more specific project interests

### ISSUE THREAD

**Issue by AldrinSeanPereira** [krshkun/krshkun#75]
### Description

In the "More about me" part

you can specify more about what your of projects you like to get involved in

this is better than the wording you have which is very general and not helpful for your profile

**Comment by krshkun** [comment]
Oh, thanks for pointing out that must have been a issue I might have made while accepting copilot suggestions in the readme, it's supposed to be:

```diff
- I'm looking for help with finding projects to contribute to!
+ I'm looking to help you in finding projects to contribute to!
```

**Comment by AldrinSeanPereira** [comment]
Awesome! 🙌🏼
